export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER = 'LOGIN_USER';

export const REGISTER_UPDATE = 'REGISTER_UPDATE';
export const REGISTER_CREATE = 'REGISTER_CREATE';
export const REGISTER_FETCH_SUCCESS = 'REGISTER_FETCH_SUCCESS';
export const REGISTER_SAVE_SUCCESS = 'REGISTER_SAVE_SUCCESS';
export const REGISTER_DELETE_SUCCESS = 'REGISTER_DELETE_SUCCESS'; 

export const GET_DISPLAYBOOK = 'GET_DISPLAYBOOK';
export const GET_DISPLAYBOOK_SUCCESS = 'GET_DISPLAYBOOK_SUCCESS';
export const GET_DISPLAYBOOK_FAILURE = 'GET_DISPLAYBOOK_FAILURE';

export const GET_CATEGORY = 'GET_CATEGORY';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAILURE = 'GET_CATEGORY_FAILURE';

export const GET_CATEGORYBOOK = 'GET_CATEGORYBOOK';
export const GET_CATEGORYBOOK_SUCCESS = 'GET_CATEGORYBOOK_SUCCESS';
export const GET_CATEGORYBOOK_FAILURE = 'GET_CATEGORYBOOK_FAILURE';

export const GET_BOOK = 'GET_BOOK';
export const GET_BOOK_SUCCESS = 'GET_BOOK_SUCCESS';
export const GET_BOOK_FAILURE = 'GET_BOOK_FAILURE';
export const GET_SIMILARBOOK = 'GET_SIMILARBOOK';
export const GET_SIMILARBOOK_SUCCESS = 'GET_SIMILARBOOK_SUCCESS';
export const GET_SIMILARBOOK_FAILURE = 'GET_SIMILARBOOK_FAILURE';

export const CEK_BELI = 'CEK_BELI';
export const CEK_BELI_SUCCESS = 'CEK_BELI_SUCCESS';
export const CEK_BELI_FAILURE = 'CEK_BELI_FAILURE';
export const POST_BELI = 'POST_BELI';
export const POST_BELI_SUCCESS = 'POST_BELI_SUCCESS';
export const POST_BELI_FAILURE = 'POST_BELI_FAILURE';

export const CEK_SEWA = 'CEK_SEWA';
export const CEK_SEWA_SUCCESS = 'CEK_SEWA_SUCCESS';
export const CEK_SEWA_FAILURE = 'CEK_SEWA_FAILURE'; 
export const POST_SEWA = 'POST_SEWA';
export const POST_SEWA_SUCCESS = 'POST_SEWA_SUCCESS';
export const POST_SEWA_FAILURE = 'POST_SEWA_FAILURE';

export const CEK_PINJAM = 'CEK_PINJAM';
export const CEK_PINJAM_SUCCESS = 'CEK_PINJAM_SUCCESS';
export const CEK_PINJAM_FAILURE = 'CEK_PINJAM_FAILURE'; 
export const POST_PINJAM = 'POST_PINJAM';
export const POST_PINJAM_SUCCESS = 'POST_PINJAM_SUCCESS';
export const POST_PINJAM_FAILURE = 'POST_PINJAM_FAILURE';

export const POST_VOUCHER = 'POST_VOUCHER';
export const POST_VOUCHER_SUCCESS = 'POST_VOUCHER_SUCCESS';
export const POST_VOUCHER_FAILURE = 'POST_VOUCHER_FAILURE';

export const POST_SEARCH = 'POST_SEARCH';
export const POST_SEARCH_SUCCESS = 'POST_SEARCH_SUCCESS';
export const POST_SEARCH_FAILURE = 'POST_SEARCH_FAILURE';

export const POST_SEARCHTEXT = 'POST_SEARCHTEXT';
export const POST_SEARCHTEXT_SUCCESS = 'POST_SEARCHTEXT_SUCCESS';
export const POST_SEARCHTEXT_FAILURE = 'POST_SEARCHTEXT_FAILURE';

export const POST_BOOKMARK = 'POST_BOOKMARK';
export const POST_BOOKMARK_SUCCESS = 'POST_BOOKMARK_SUCCESS';
export const POST_BOOKMARK_FAILURE = 'POST_BOOKMARK_FAILURE';
export const CEK_BOOKMARK = 'CEK_BOOKMARK';
export const CEK_BOOKMARK_SUCCESS = 'CEK_BOOKMARK_SUCCESS';
export const CEK_BOOKMARK_FAILURE = 'CEK_BOOKMARK_FAILURE';

export const GET_KOLEKSI = 'GET_KOLEKSI';
export const GET_KOLEKSI_SUCCESS = 'GET_KOLEKSI_SUCCESS';
export const GET_KOLEKSI_FAILURE = 'GET_KOLEKSI_FAILURE';